# Generated by Django 5.2 on 2025-04-19 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="email",
            new_name="emailIn",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="name",
            new_name="nameIn",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="phone",
            new_name="phoneIn",
        ),
    ]
