# Generated by Django 5.2 on 2025-04-19 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0004_rename_user_asd"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="asd",
            new_name="User",
        ),
    ]
