# Generated by Django 5.2 on 2025-04-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0005_rename_asd_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assignedto",
            field=models.ManyToManyField(
                blank=True, related_name="assignedto", to="join.contact"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="subtasks",
            field=models.ManyToManyField(
                blank=True, related_name="subtasks", to="join.subtasks"
            ),
        ),
    ]
