# Generated by Django 5.2 on 2025-04-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0006_alter_task_assignedto_alter_task_subtasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="subtasks",
        ),
        migrations.AddField(
            model_name="subtasks",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="join.task",
            ),
        ),
        migrations.AlterField(
            model_name="subtasks",
            name="status",
            field=models.CharField(
                choices=[("todo", "To Do"), ("inwork", "In Work"), ("done", "Done")],
                default="todo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="color",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="task",
            name="inits",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
