# Generated by Django 5.2 on 2025-04-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0007_remove_task_subtasks_subtasks_task_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assignedto",
        ),
        migrations.AddField(
            model_name="task",
            name="assignedto",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
