# Generated by Django 5.2 on 2025-04-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0008_remove_task_assignedto_task_assignedto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awaitfeedback", models.CharField(max_length=50)),
                ("done", models.CharField(max_length=50)),
                ("inprogress", models.CharField(max_length=50)),
                ("todo", models.CharField(max_length=50)),
                ("urgent", models.CharField(max_length=50)),
            ],
        ),
    ]
