# Generated by Django 5.2 on 2025-04-19 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0009_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtasks",
            name="task",
            field=models.ForeignKey(
                blank=True,
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="join.task",
            ),
        ),
    ]
