# Generated by Django 5.2 on 2025-04-19 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0010_alter_subtasks_task"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subtasks",
        ),
    ]
