# Generated by Django 5.2 on 2025-04-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0011_delete_subtasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="subtasks",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
