# Generated by Django 5.2 on 2025-04-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0013_remove_task_subtasks_subtask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assignedto",
        ),
        migrations.AddField(
            model_name="task",
            name="assignedto",
            field=models.ManyToManyField(
                blank=True, related_name="assignedto", to="join.contact"
            ),
        ),
    ]
