# Generated by Django 5.2 on 2025-04-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0014_remove_task_assignedto_task_assignedto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="color",
        ),
        migrations.AddField(
            model_name="task",
            name="colors",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
