# Generated by Django 5.2 on 2025-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0015_remove_task_color_task_colors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="colors",
        ),
        migrations.AddField(
            model_name="task",
            name="color",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
