# Generated by Django 5.2 on 2025-04-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0017_alter_subtask_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtask",
                to="join.task",
            ),
        ),
    ]
