# Generated by Django 5.2 on 2025-04-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0018_alter_subtask_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("User Story", "User Story"),
                    ("Technical Task", "Technical Task"),
                ],
                max_length=100,
            ),
        ),
    ]
