# Generated by Django 5.2 on 2025-04-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0020_alter_task_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="color",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
