# Generated by Django 5.2 on 2025-04-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0023_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentuser",
            name="emailIn",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="currentuser",
            name="phoneIn",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
