# Generated by Django 5.2 on 2025-04-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0024_currentuser_emailin_currentuser_phonein"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentuser",
            name="token",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
