# Generated by Django 5.2 on 2025-04-23 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0026_remove_contact_user_contact_users_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="users",
            new_name="user",
        ),
    ]
