# Generated by Django 5.2 on 2025-04-23 23:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("join", "0029_alter_currentuser_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ManyToManyField(
                blank=True, related_name="task_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
